# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 118a2d0dedbede4b79445bcfde798856b1580dec4f281ccfb8e7ac423c25a9cb7b1bc47bce1eff0fb087d93fde3406594379a10a5593701c97a806292c24ee6f

test:
  secret_key_base: 0ab549c988e6b83ba2aa7887329ef645272792479bac2c25ff51aef371a99744b1cd461441faf79bd340421cb3bdd85149928207cd7b80451d668d655cf59c64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
